### ISSUE TITLE
Check

### ISSUE THREAD

**Issue by askhan963** [m-palaciosq/CampusCollabConnect#2]
Hi there!
I am the one from the platform. Can we have a discussion here?

**Comment by m-palaciosq** [comment]
discuss what
________________________________
From: Muhammad Awais Khan ***@***.***>
Sent: Monday, March 25, 2024 10:17 AM
To: m-palaciosq/CampusCollabConnect ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [m-palaciosq/CampusCollabConnect] Check (Issue #2)


Hi there!
I am the one from the platform. Can we have a discussion here?

**Comment by askhan963** [comment]
Just wanted to tell before you assigned me but let it be for now. And
please don't let the support know about this that I contacted you in here.
